const rooms = [
  {
    type: "Standard Room",
    price: 1499,
    capacity: "2 Persons",
    size: "200 sq.ft",
    description: "Comfortable room with all essential amenities for a pleasant stay",
    image: "/images/standard-room.jpg",
    amenities: ["Free WiFi", "TV", "AC", "Room Service", "Attached Bathroom"],
    popular: false,
  },
  {
    type: "Deluxe Room",
    price: 2499,
    capacity: "2 Persons",
    size: "280 sq.ft",
    description: "Spacious deluxe accommodation with premium furnishings and city views",
    image: "/images/deluxe-room.jpg",
    amenities: ["Free WiFi", "Smart TV", "Mini Bar", "AC", "Balcony", "Bathtub"],
    popular: true,
  },
  {
    type: "Suite",
    price: 3999,
    capacity: "3 Persons",
    size: "400 sq.ft",
    description: "Luxurious suite with separate living area and panoramic views",
    image: "/images/suite.jpg",
    amenities: ["Free WiFi", "55\" TV", "Living Room", "AC", "Jacuzzi", "Butler Service"],
    popular: false,
  },
  {
    type: "Family Room",
    price: 4999,
    capacity: "4 Persons",
    size: "450 sq.ft",
    description: "Perfect for families with extra space and kid-friendly amenities",
    image: "/images/family-room.jpg",
    amenities: ["Free WiFi", "2 TVs", "Kitchenette", "AC", "2 Bathrooms", "Play Area"],
    popular: false,
  },
]